### ISSUE TITLE
VMM Express SLB issue

### ISSUE THREAD

**Issue by KennyMacCormik** [Microsoft/SDN#129]
Greetings,

I'm using VMM Express script to install NC and SLB. Both services are deploying fine, but when script tries to add SLB to NC the following errors throuwn

![image](https://user-images.githubusercontent.com/20319654/30967009-85a6fc9a-a463-11e7-9b5e-f52a82a7f3d0.png)

I've tried to add SLB manually and got the following error

![image](https://user-images.githubusercontent.com/20319654/30967076-babefa86-a463-11e7-91ae-9c979047316c.png)

I've verified that no IP addressed are allocated for the private VIP and public VIP pools. I've enabled debug logging and found out the following errors in the SDNSlbManager debug log

```
09/28/2017 12:35:18, SDNSLBM, 16, 0, PRIMARY#37,sdnslbm\slbmservice\SlbmUtils.cs#Entered ConfigureOrUnconfigureSlbmVipOnStack ...
```
```
09/28/2017 12:35:18, SDNSLBM, 16, 0, PRIMARY#181,Utilities\Runtime\ConfigManager.cs#GetConfigSetting (SLB.SlbManagerVips): GetPropertyAsync failed: Property does not exist.
````
```
09/28/2017 12:35:18, SDNSLBM, 16, 0, PRIMARY#61,sdnslbm\slbmservice\SlbmUtils.cs#EXCEPTION: Failed to Add slbm ip adderess  on loopback inteface. Exiting..
```
```
09/28/2017 12:35:18, SDNSLBM, 16, 0, PRIMARY#61,sdnslbm\slbmservice\SlbmUtils.cs#Message: Configuration setting "SlbManagerVips" not found under "SLB", Target: SlbManagerVips, InnerException: null, Exception: Microsoft.Windows.Networking.NetworkController.Framework.Utilities.NCElementNotFoundException: Configuration setting "SlbManagerVips" not found under "SLB"
   at Microsoft.Windows.Networking.NetworkController.Framework.Utilities.ConfigManager.GetConfigSetting(ConfigNamespace namespaceId, String paramName)
   at Microsoft.Windows.Networking.NetworkController.SLBManager.SlbManagerService.ConfigureOrUnconfigureSlbmVipOnStack(AddressUpdateType UpdateType)

```
```
09/28/2017 12:35:18, SDNSLBM, 16, 0, PRIMARY#45,sdnslbm\slbmservice\SlbmUtils.cs#Exited ConfigureOrUnconfigureSlbmVipOnStack
```

Both NC and SLB services are successfully configured via installation scripts with no manual involvement.

If I query NC REST API I can see that the configuration is stored in NC, but for some reason not being able to propagate to the SLBs

```
{
  "resourceRef": "/loadBalancerManager/config",
  "resourceId": "config",
  "resourceMetadata": {
    "resourceName": "config"
  },
  "etag": "W/\"abddef5a-f2fd-4578-bfaf-eba8346ff346\"",
  "instanceId": "34171e26-480e-4498-886c-27241de15bbd",
  "properties": {
    "provisioningState": "Failed",
    "loadBalancerManagerIPAddress": "172.16.0.254",
    "outboundNatIPExemptions": [],
    "vipIpPools": [
      {
        "resourceRef": "/logicalnetworks/d4f5d3a7-1b40-462f-9ee7-e75f02a6b130/subnets/f22621ce-4288-43d4-b7f0-3dd070d3b3b0/ipPools/8955a758-87bb-49a9-ae95-2af8c60be6e4"
      },
      {
        "resourceRef": "/logicalnetworks/bf6542ca-b48c-4ca3-9bc8-6acfeee1b0ee/subnets/c1ed6087-fe71-4d24-b96e-2a1fb643e61c/ipPools/6bb9f1bf-59b3-4688-80ac-57dad452d8c3"
      }
    ]
  }
}
```
```
{
  "resourceRef": "/logicalnetworks/d4f5d3a7-1b40-462f-9ee7-e75f02a6b130/subnets/f22621ce-4288-43d4-b7f0-3dd070d3b3b0/ipPools/8955a758-87bb-49a9-ae95-2af8c60be6e4",
  "resourceId": "8955a758-87bb-49a9-ae95-2af8c60be6e4",
  "resourceMetadata": {
    "resourceName": "PrivateVIP_IPAddressPool_0"
  },
  "etag": "W/\"950527c7-0b64-4338-a28a-af9a9ba97aa3\"",
  "instanceId": "ccb1127e-9fd4-4010-a957-2d715b7e11f8",
  "properties": {
    "provisioningState": "Succeeded",
    "startIpAddress": "172.16.0.1",
    "endIpAddress": "172.16.0.254",
    "usage": {
      "numberOfIPAddresses": 254,
      "numberofIPAddressesAllocated": 1,
      "numberOfIPAddressesInTransition": 0
    },
    "loadBalancerManager": {
      "resourceRef": "/loadBalancerManager/config"
    }
  }
}
```
I've tried to pass different IPs for the SLB Manager VIP (the last one from the Private VIP pool, the first one, random one in the middle) but all re configurations failed as well. All the time I see the same responses from the REST interface, only  "loadBalancerManagerIPAddress": "172.16.0.254" changes to the appropriate IPs.

**Comment by realjonas** [comment]
Have the same problem, did you ever solved this?
/J

**Comment by KennyMacCormik** [comment]
Hi,

Try checking Trusted Root for the certificates that are not self-signed on NC, VMHosts and SLB. If there are any, remove them

**Comment by realjonas** [comment]
I have checked the certificates and they look ok. 

/j

**Comment by KennyMacCormik** [comment]
I've never fixed this particular issue in fact. I've just reinstalled both NC and SLB. From my understanding this is happening due to some certificates misconfiguration. In my case I was using CA signed. After I've reinstalled, I've tried self-signed and it worked. So, are you using CA signed or not?

**Comment by realjonas** [comment]
I’m using self signed cert and everything seams working exept onboarding slb
/j

**Comment by KennyMacCormik** [comment]
Unfortunately I'm afraid I cannot be more helpful. My case was resolved by changing certificates to self-signed and reinstalling NC and SLB. I really believe this is authentication issue of some sort, but I can't tell you more.

**Comment by realjonas** [comment]
Ok, thank you and Merry Christmas

/j

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
